### PR TITLE
Membership

### PR DESCRIPTION
**Pull request by JBonser**
Added team membership endpoints and associated tests.

POST /memberships/
GET /memberships/
GET /memberships/?team_id

### CODE REVIEW

**Review by GlennEastham — COMMENTED** [review]
__tablename__ = "team_role"
    __tablename__ = "team_roles"

Can we keep the table names singular as a standard please old chum

**Comment by JBonser** [comment]
So I've just been reading up on this debate between pluralisation of table names: I think this article sums up how I feel about it:
https://medium.com/@fbnlsr/the-table-naming-dilemma-singular-vs-plural-dc260d90aaff
What is an issue here is that the team_role table should have been called team_roles to be in line with all the other tables in the db:
* users
* teams
* memberships

I would rather spin off the fix for the table name of team_role in a different PR if that's okay as it will require changes to the migration scripts as well.

**Comment by JBonser** [comment]
annnnnd I've just realised it was this PR that changed the name of the table name so I actually missed updating the migration file. I will update that in a new commit.

**Comment by GlennEastham** [comment]
I've preferred singular for when I'm constructing SQL statements but since we're using an ORM and you can just give the table an alias in the statement if desired, it makes it irrelevant.

**Review by GlennEastham — APPROVED** [review]

**Pull request merged**
